### PR TITLE
4.0 updates

### PR DESCRIPTION
**Pull request by dndrks**
_a gathering mechanism for changes to the crow Max + M4L libraries!_

### done + tested
**Max objects**:
- all `crow.` objects have received stability, syntax, and cosmetic updates
- added `shape` to `crow.adsr`, `crow.ar` and `crow.volts`
- fixed `crow.var` errors when sending messages prepended with 'mode' (which happens a lot with input-behavior patching)
- add 3.0's `input` modes to `crow.inputs.gui`
- #34 
- update `crow.inputs` help patcher + ref files
- renamed `crow.makefunction` to `crow.dyn`, as dynamic variables now have wider usage in 3.0+
- removed `crow.lfo` as patching slope-generating objects (eg. [line] and [ramp~]) to `crow.volts` allows for more capability within Max
- removed outdated API calls
- removed `bootloader.maxpat`, as druid offers easier + more robust solutions
- updated all help patchers to demonstrate new patching opportunities with the `crow.` object changes
- updated all ref pages to document new inputs + arguments

**M4L devices**:
- added `^^osc` device to create audio-rate oscillators at crow outputs
- quick fix for `^^command_center` (https://github.com/monome/crow-max-and-m4l/issues/34)
- refine `^^geode` device for general release
- updated PDF doc for 4.0
- quick fix for theme text elements issue

### CODE REVIEW

**Comment by dndrks** [comment]
@trentgill , got everything squared up for updating the `crow.` objects -- if it's possible for you to work from the [v4.0 branch](https://github.com/monome/crow-max-and-m4l/tree/v4.0) for #32, that'd be rad!!

v easy to grab all the new stuff, but just in case: https://github.com/monome/crow-max-and-m4l/archive/refs/heads/v4.0.zip

**Comment by dndrks** [comment]
@trentgill , alright i think that's it (excepting #32) ! we've got a new device, a buncha refinements, and all docs up to date!

**Comment by trentgill** [comment]
@dndrks sounds great! i'm going to get this first pass on the new crow libraries finished, then post up the firmware on discord for feedback on firmware & docs, then will dive into #32 which hopefully isn't *too* much of rabbit hole...

**Comment by dndrks** [comment]
@trentgill , the freezing fix works on my end, so rolling it all up and in for 4.0's release!

**Pull request merged**
